<?php
namespace App\Services;
use App\Enums\{AuditEventType,DisbursementStage,RoleCode}; use App\Models\{DisbursementApproval,DisbursementRequest,DisbursementStatusHistory,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class ApprovalService
{
    public function __construct(private AuditService $auditService) {}
    public function branchApprove(DisbursementRequest $r,array $d,User $a): DisbursementRequest { return $this->approve($r,DisbursementStage::SUBMITTED,DisbursementStage::BRANCH_APPROVED,RoleCode::BRANCH_MANAGER,$d,$a); }
    public function financeReview(DisbursementRequest $r,array $d,User $a): DisbursementRequest { return $this->approve($r,DisbursementStage::BRANCH_APPROVED,DisbursementStage::FINANCE_REVIEWED,RoleCode::FINANCE_OFFICER,$d,$a); }
    public function authorize(DisbursementRequest $r,array $d,User $a): DisbursementRequest { return $this->approve($r,DisbursementStage::FINANCE_REVIEWED,DisbursementStage::AUTHORIZED,RoleCode::SUPER_ADMIN,$d,$a,true); }
    private function approve(DisbursementRequest $r,DisbursementStage $expected,DisbursementStage $next,RoleCode $role,array $d,User $a,bool $auth=false): DisbursementRequest { return DB::transaction(function() use($r,$expected,$next,$role,$d,$a,$auth){$r=DisbursementRequest::whereKey($r->id)->lockForUpdate()->firstOrFail(); if($r->stage!==$expected->value) throw ValidationException::withMessages(['stage'=>"Expected {$expected->value}, got {$r->stage}."]); if(DisbursementApproval::where('disbursement_request_id',$r->id)->where('stage',$next->value)->exists()) throw ValidationException::withMessages(['approval'=>'This approval stage has already been recorded.']); DisbursementApproval::create(['disbursement_request_id'=>$r->id,'user_id'=>$a->id,'role_code'=>$role->value,'stage'=>$next->value,'remarks'=>$d['remarks']??null,'approved_at'=>now()]); $update=['stage'=>$next->value]; if($auth){$update['authorized_by']=$a->id;$update['authorized_at']=now();} $r->update($update); DisbursementStatusHistory::create(['disbursement_request_id'=>$r->id,'from_stage'=>$expected->value,'to_stage'=>$next->value,'reason'=>$d['remarks']??"Approved by {$role->value}",'changed_by'=>$a->id]); $this->auditService->record($a,AuditEventType::APPROVAL,"Disbursement approval: {$next->value}",$r,['role'=>$role->value]); return $r->refresh()->load(['member','approvals','statusHistories']);}); }
}
