<?php
namespace App\Services;
use App\Enums\{AuditEventType,MemberStatus}; use App\Models\{Member,MemberStatusHistory,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class MemberService
{
    public function __construct(private AuditService $auditService) {}
    public function create(array $data, User $actor): Member { return DB::transaction(function() use($data,$actor){ $m=Member::create([...$data,'created_by'=>$actor->id,'updated_by'=>$actor->id,'status'=>MemberStatus::PENDING->value]); $this->history($m,null,MemberStatus::PENDING->value,'Member created',$actor); $this->auditService->record($actor,AuditEventType::CREATE,'Member created',$m); return $m->load('statusHistories'); }); }
    public function update(Member $m,array $data,User $actor): Member { return DB::transaction(function() use($m,$data,$actor){$m=Member::whereKey($m->id)->lockForUpdate()->firstOrFail();$before=$m->only(array_keys($data));$m->update([...$data,'updated_by'=>$actor->id]);$this->auditService->record($actor,AuditEventType::UPDATE,'Member updated',$m,['before'=>$before,'after'=>$m->only(array_keys($data))]);return $m->refresh()->load('statusHistories');}); }
    public function verify(Member $m,array $d,User $a): Member { return $this->transition($m,MemberStatus::PENDING,MemberStatus::VERIFIED,$d['reason']??'KYC verified',$a); }
    public function activate(Member $m,array $d,User $a): Member { if(!preg_match('/^UMID-\d{4}-\d{6}$/',$m->umid)) throw ValidationException::withMessages(['umid'=>'Invalid UMID format.']); return $this->transition($m,MemberStatus::VERIFIED,MemberStatus::ACTIVE,$d['reason']??'Activated',$a,['activated_at'=>now()]); }
    public function suspend(Member $m,array $d,User $a): Member { return $this->transition($m,MemberStatus::ACTIVE,MemberStatus::SUSPENDED,$d['reason']??'Suspended',$a); }
    public function reactivate(Member $m,array $d,User $a): Member { return $this->transition($m,MemberStatus::SUSPENDED,MemberStatus::ACTIVE,$d['reason']??'Reactivated',$a); }
    public function terminate(Member $m,array $d,User $a): Member { if(empty($d['reason'])) throw ValidationException::withMessages(['reason'=>'Termination reason is required.']); return DB::transaction(function() use($m,$d,$a){$m=Member::whereKey($m->id)->lockForUpdate()->firstOrFail();$from=$m->status;$m->update(['status'=>MemberStatus::TERMINATED->value,'status_reason'=>$d['reason'],'terminated_at'=>now(),'updated_by'=>$a->id]);$this->history($m,$from,MemberStatus::TERMINATED->value,$d['reason'],$a);$this->auditService->record($a,AuditEventType::STATUS_CHANGE,'Member terminated',$m,['from'=>$from,'to'=>MemberStatus::TERMINATED->value]);return $m->refresh()->load('statusHistories');}); }
    private function transition(Member $m,MemberStatus $expected,MemberStatus $next,string $reason,User $a,array $extra=[]): Member { return DB::transaction(function() use($m,$expected,$next,$reason,$a,$extra){$m=Member::whereKey($m->id)->lockForUpdate()->firstOrFail(); if($m->status!==$expected->value) throw ValidationException::withMessages(['status'=>"Expected {$expected->value}, got {$m->status}."]); $m->update([...$extra,'status'=>$next->value,'status_reason'=>$reason,'updated_by'=>$a->id]); $this->history($m,$expected->value,$next->value,$reason,$a); $this->auditService->record($a,AuditEventType::STATUS_CHANGE,"Member status changed to {$next->value}",$m,['from'=>$expected->value,'to'=>$next->value]); return $m->refresh()->load('statusHistories');}); }
    private function history(Member $m,?string $from,string $to,string $reason,User $a): void { MemberStatusHistory::create(['member_id'=>$m->id,'from_status'=>$from,'to_status'=>$to,'reason'=>$reason,'changed_by'=>$a->id]); }
}
