<?php
namespace App\Services;
use App\Enums\{AuditEventType,MonthlyPeriodStatus,ReconciliationItemStatus,SeverityLevel}; use App\Models\{MonthlyPeriod,ReconciliationItem,ReconciliationRun,TreasuryTransaction,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class PeriodService
{
    public function __construct(private AuditService $auditService) {}
    public function create(array $data,User $actor): MonthlyPeriod {$p=MonthlyPeriod::create(['name'=>$data['name'],'month'=>$data['month'],'year'=>$data['year'],'status'=>MonthlyPeriodStatus::OPEN->value,'opening_balance'=>$data['opening_balance']??0]);$this->auditService->record($actor,AuditEventType::CREATE,'Monthly period created',$p);return $p;}
    public function review(MonthlyPeriod $p,array $d,User $a): MonthlyPeriod{return $this->transition($p,MonthlyPeriodStatus::OPEN,MonthlyPeriodStatus::REVIEW,$a,$d['reason']??'Moved to review');}
    public function close(MonthlyPeriod $p,array $d,User $a): MonthlyPeriod{return DB::transaction(function() use($p,$d,$a){$p=MonthlyPeriod::whereKey($p->id)->lockForUpdate()->firstOrFail(); if($p->status!==MonthlyPeriodStatus::REVIEW->value) throw ValidationException::withMessages(['status'=>'Only REVIEW periods can be closed.']); $run=ReconciliationRun::where('monthly_period_id',$p->id)->latest()->first(); if(!$run) throw ValidationException::withMessages(['reconciliation'=>'Run reconciliation before closing the period.']); $blocking=ReconciliationItem::where('reconciliation_run_id',$run->id)->whereIn('severity',[SeverityLevel::HIGH->value,SeverityLevel::CRITICAL->value])->whereIn('status',[ReconciliationItemStatus::OPEN->value,ReconciliationItemStatus::UNDER_REVIEW->value])->exists(); if($blocking) throw ValidationException::withMessages(['reconciliation'=>'Unresolved HIGH/CRITICAL reconciliation blockers prevent close.']); $p->update(['status'=>MonthlyPeriodStatus::CLOSED->value,'closing_balance'=>TreasuryTransaction::where('monthly_period_id',$p->id)->latest('id')->value('balance_after')??$p->opening_balance,'closed_by'=>$a->id,'closed_at'=>now()]);$this->auditService->record($a,AuditEventType::PERIOD_CLOSE,'Monthly period closed',$p);return $p->refresh();});}
    public function lock(MonthlyPeriod $p,array $d,User $a): MonthlyPeriod{return DB::transaction(function() use($p,$a){$p=MonthlyPeriod::whereKey($p->id)->lockForUpdate()->firstOrFail(); if($p->status!==MonthlyPeriodStatus::CLOSED->value) throw ValidationException::withMessages(['status'=>'Only CLOSED periods can be locked.']); $p->update(['status'=>MonthlyPeriodStatus::LOCKED->value,'locked_by'=>$a->id,'locked_at'=>now()]);$this->auditService->record($a,AuditEventType::PERIOD_LOCK,'Monthly period locked',$p);return $p->refresh();});}
    public function reopen(MonthlyPeriod $p,array $d,User $a): MonthlyPeriod{return DB::transaction(function() use($p,$a){$p=MonthlyPeriod::whereKey($p->id)->lockForUpdate()->firstOrFail(); if($p->status===MonthlyPeriodStatus::LOCKED->value) throw ValidationException::withMessages(['status'=>'LOCKED periods cannot be reopened in MVP.']); if($p->status!==MonthlyPeriodStatus::CLOSED->value) throw ValidationException::withMessages(['status'=>'Only CLOSED periods can be reopened.']); $p->update(['status'=>MonthlyPeriodStatus::REVIEW->value,'closed_by'=>null,'closed_at'=>null]);$this->auditService->record($a,AuditEventType::STATUS_CHANGE,'Monthly period reopened',$p);return $p->refresh();});}
    private function transition(MonthlyPeriod $p,MonthlyPeriodStatus $e,MonthlyPeriodStatus $n,User $a,string $reason): MonthlyPeriod{return DB::transaction(function() use($p,$e,$n,$a,$reason){$p=MonthlyPeriod::whereKey($p->id)->lockForUpdate()->firstOrFail(); if($p->status!==$e->value) throw ValidationException::withMessages(['status'=>"Expected {$e->value}, got {$p->status}."]); $p->update(['status'=>$n->value]);$this->auditService->record($a,AuditEventType::STATUS_CHANGE,"Period moved to {$n->value}",$p,['reason'=>$reason]);return $p->refresh();});}
}
