<?php
namespace App\Services;
use App\Enums\{AuditEventType,ReconciliationItemStatus,SeverityLevel}; use App\Models\{DisbursementRequest,MonthlyPeriod,ReconciliationItem,ReconciliationRun,TreasuryTransaction,User}; use Illuminate\Support\Facades\DB;
class ReconciliationService
{
    public function __construct(private AuditService $auditService) {}
    public function run(MonthlyPeriod $period,User $actor): ReconciliationRun { return DB::transaction(function() use($period,$actor){$ledger=(float)TreasuryTransaction::where('monthly_period_id',$period->id)->sum('amount');$operational=(float)DisbursementRequest::where('stage','PAID')->sum('amount')*-1;$variance=round($ledger-$operational,2);$run=ReconciliationRun::create(['monthly_period_id'=>$period->id,'triggered_by'=>$actor->id,'status'=>'COMPLETED','operational_total'=>$operational,'ledger_total'=>$ledger,'variance'=>$variance,'completed_at'=>now()]); if(abs($variance)>0){ReconciliationItem::create(['reconciliation_run_id'=>$run->id,'severity'=>abs($variance)>=10000?SeverityLevel::HIGH->value:SeverityLevel::MEDIUM->value,'status'=>ReconciliationItemStatus::OPEN->value,'description'=>'Ledger total does not match operational paid disbursement total.','variance'=>$variance]);} $this->auditService->record($actor,AuditEventType::IMPORT,'Reconciliation run completed',$run,['variance'=>$variance]); return $run->load('items');}); }
    public function markUnderReview(ReconciliationItem $i,User $a): ReconciliationItem { return $this->transitionItem($i,ReconciliationItemStatus::UNDER_REVIEW->value,'Marked under review',$a); }
    public function resolve(ReconciliationItem $i,array $d,User $a): ReconciliationItem { return $this->transitionItem($i,ReconciliationItemStatus::RESOLVED->value,$d['resolution_note'],$a); }
    public function override(ReconciliationItem $i,array $d,User $a): ReconciliationItem { return $this->transitionItem($i,ReconciliationItemStatus::OVERRIDDEN->value,$d['resolution_note'],$a); }
    private function transitionItem(ReconciliationItem $i,string $status,string $note,User $a): ReconciliationItem { return DB::transaction(function() use($i,$status,$note,$a){$i=ReconciliationItem::whereKey($i->id)->lockForUpdate()->firstOrFail();$i->update(['status'=>$status,'resolved_by'=>in_array($status,[ReconciliationItemStatus::RESOLVED->value,ReconciliationItemStatus::OVERRIDDEN->value],true)?$a->id:$i->resolved_by,'resolved_at'=>now(),'resolution_note'=>$note]);$this->auditService->record($a,AuditEventType::OVERRIDE,"Reconciliation item moved to {$status}",$i);return $i->refresh();}); }
}
