<?php
namespace App\Services;
use App\Enums\{AuditEventType,DisbursementStage,MonthlyPeriodStatus,TreasuryTransactionType}; use App\Models\{DisbursementRequest,MonthlyPeriod,TreasuryTransaction,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class TreasuryService
{
    public function __construct(private AuditService $auditService, private OperationalLogger $operationalLogger) {}
    public function currentBalance(): float { return (float)(TreasuryTransaction::latest('id')->value('balance_after') ?? 0); }
    public function postDisbursementPaid(DisbursementRequest $request,array $data,User $actor): TreasuryTransaction { return DB::transaction(function() use($request,$data,$actor){$request=DisbursementRequest::whereKey($request->id)->lockForUpdate()->firstOrFail(); if($request->stage!==DisbursementStage::AUTHORIZED->value){$this->operationalLogger->blocked('payment_before_authorization',['disbursement_request_id'=>$request->id]); throw ValidationException::withMessages(['stage'=>'Only AUTHORIZED requests can be marked as paid.']);} if(TreasuryTransaction::where('disbursement_request_id',$request->id)->where('type',TreasuryTransactionType::DISBURSEMENT_PAID->value)->exists()){$this->operationalLogger->blocked('duplicate_payout_attempt',['disbursement_request_id'=>$request->id]); throw ValidationException::withMessages(['payment'=>'This request has already been paid.']);} $tx=$this->post(MonthlyPeriod::findOrFail($data['monthly_period_id']),TreasuryTransactionType::DISBURSEMENT_PAID,-abs((float)$request->amount),[...$data,'description'=>$data['description']??'Disbursement paid','disbursement_request_id'=>$request->id],$actor); $request->update(['stage'=>DisbursementStage::PAID->value,'paid_at'=>now()]); $this->auditService->record($actor,AuditEventType::PAYMENT,'Disbursement marked as paid',$request,['treasury_transaction_id'=>$tx->id]); $this->operationalLogger->financial('disbursement_paid',['disbursement_request_id'=>$request->id,'treasury_transaction_id'=>$tx->id]); return $tx->load('disbursementRequest');}); }
    private function post(MonthlyPeriod $period,TreasuryTransactionType $type,float $amount,array $data,User $actor): TreasuryTransaction { return DB::transaction(function() use($period,$type,$amount,$data,$actor){$period=MonthlyPeriod::whereKey($period->id)->lockForUpdate()->firstOrFail(); if(in_array($period->status,[MonthlyPeriodStatus::CLOSED->value,MonthlyPeriodStatus::LOCKED->value],true)){throw ValidationException::withMessages(['period'=>'Cannot post into closed or locked period.']);} $balance=$this->currentBalance()+$amount; $tx=TreasuryTransaction::create(['monthly_period_id'=>$period->id,'disbursement_request_id'=>$data['disbursement_request_id']??null,'created_by'=>$actor->id,'reversed_transaction_id'=>$data['reversed_transaction_id']??null,'type'=>$type->value,'amount'=>$amount,'balance_after'=>$balance,'description'=>$data['description']??null,'remarks'=>$data['remarks']??null,'occurred_on'=>$data['occurred_on']??now()->toDateString()]); $this->auditService->record($actor,AuditEventType::PAYMENT,"Treasury transaction posted: {$type->value}",$tx,['amount'=>$amount,'balance_after'=>$balance]); return $tx;}); }
}
