<?php
namespace App\Services;
use App\Enums\{AuditEventType,ImportBatchStatus,ImportRowStatus}; use App\Models\{ImportBatch,ImportRow,ImportSheetSnapshot,TrialBalanceRecord,User}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class WorkbookImportService
{
    public function __construct(private AuditService $auditService) {}
    public function createBatch(array $d,User $a): ImportBatch {$b=ImportBatch::create(['uploaded_by'=>$a->id,'filename'=>$d['filename'],'status'=>ImportBatchStatus::UPLOADED->value,'metadata'=>$d['metadata']??[]]);$this->auditService->record($a,AuditEventType::IMPORT,'Workbook import batch created',$b);return $b;}
    public function addSheet(ImportBatch $b,array $d,User $a): ImportSheetSnapshot {$s=$b->sheets()->create(['sheet_name'=>$d['sheet_name'],'title_blocks'=>$d['title_blocks']??[],'heading_map'=>$d['heading_map']??[],'raw_payload'=>$d['raw_payload']??[]]);$this->auditService->record($a,AuditEventType::IMPORT,'Workbook sheet snapshot captured',$s);return $s;}
    public function addRows(ImportSheetSnapshot $s,array $rows,User $a): array {return DB::transaction(function() use($s,$rows,$a){$created=[];foreach($rows as $r){$created[]=ImportRow::create(['import_batch_id'=>$s->import_batch_id,'import_sheet_snapshot_id'=>$s->id,'row_number'=>$r['row_number'],'status'=>ImportRowStatus::PENDING->value,'raw_payload'=>$r['raw_payload'],'mapped_payload'=>null,'errors'=>[]]);}$this->auditService->record($a,AuditEventType::IMPORT,'Workbook rows staged',$s,['rows_count'=>count($created)]);return $created;});}
    public function mapRows(ImportBatch $b,User $a): ImportBatch {return DB::transaction(function() use($b,$a){foreach($b->rows()->where('status',ImportRowStatus::PENDING->value)->get() as $r){$raw=$r->raw_payload??[];$r->update(['status'=>ImportRowStatus::MAPPED->value,'mapped_payload'=>['label'=>$raw['label']??$raw['description']??$raw['account']??null,'amount'=>$raw['amount']??$raw['debit']??$raw['credit']??null,'source_row'=>$r->row_number],'errors'=>[]]);}$b->update(['status'=>ImportBatchStatus::MAPPED->value]);$this->auditService->record($a,AuditEventType::IMPORT,'Workbook rows mapped',$b);return $b->refresh()->load('sheets','rows');});}
    public function validateRows(ImportBatch $b,User $a): ImportBatch {return DB::transaction(function() use($b,$a){foreach($b->rows()->whereIn('status',[ImportRowStatus::MAPPED->value,ImportRowStatus::PENDING->value])->get() as $r){$m=$r->mapped_payload??[];$err=[];if(empty($m['label']))$err[]='Missing label/description/account.';if(!isset($m['amount'])||!is_numeric($m['amount']))$err[]='Missing or invalid amount.';$r->update(['status'=>count($err)?ImportRowStatus::INVALID->value:ImportRowStatus::VALID->value,'errors'=>$err]);}$has=$b->rows()->where('status',ImportRowStatus::INVALID->value)->exists();$b->update(['status'=>$has?ImportBatchStatus::FAILED->value:ImportBatchStatus::VALIDATED->value]);$this->auditService->record($a,AuditEventType::IMPORT,'Workbook rows validated',$b,['has_invalid'=>$has]);return $b->refresh()->load('sheets','rows');});}
    public function postTrialBalance(ImportBatch $b,array $d,User $a): ImportBatch {return DB::transaction(function() use($b,$d,$a){$rows=$b->rows()->where('status',ImportRowStatus::VALID->value)->get();if($rows->isEmpty())throw ValidationException::withMessages(['rows'=>'No valid rows available to post.']);foreach($rows as $r){$m=$r->mapped_payload;TrialBalanceRecord::create(['monthly_period_id'=>$d['monthly_period_id'],'source'=>$d['source']??$b->filename,'label'=>$m['label'],'amount'=>$m['amount'],'metadata'=>['import_batch_id'=>$b->id,'import_row_id'=>$r->id,'source_row'=>$m['source_row']??$r->row_number]]);$r->update(['status'=>ImportRowStatus::POSTED->value]);}$b->update(['status'=>ImportBatchStatus::POSTED->value]);$this->auditService->record($a,AuditEventType::IMPORT,'Trial balance rows posted from workbook import',$b,['posted_rows'=>$rows->count()]);return $b->refresh()->load('sheets','rows');});}
    public function skipRow(ImportRow $r,User $a): ImportRow {$r->update(['status'=>ImportRowStatus::SKIPPED->value]);$this->auditService->record($a,AuditEventType::IMPORT,'Workbook import row skipped',$r);return $r->refresh();}
}
