import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowUpRight, CheckCircle2, CircleAlert, Clock3, FileCheck2, HandCoins, UsersRound } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { dashboard } from "@/lib/api/client";
import { roleLabel } from "@/lib/api/mock";
import type { DashboardData, DisbursementStage, MemberStatus } from "@/lib/api/types";
import { Badge } from "./ui/badge";

const money = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });
const compact = new Intl.NumberFormat("en-NG", { notation: "compact", maximumFractionDigits: 1 });
const stageLabel = (stage: DisbursementStage) => stage.replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
const statusLabel = (status: MemberStatus) => status.toLowerCase().replace(/(^|_)\S/g, (letter) => letter.toUpperCase());

export function dashboardQuery(user: NonNullable<ReturnType<typeof useAuth>["user"]>) { return { queryKey: ["dashboard", user.id], queryFn: () => dashboard(user) }; }

export function Dashboard() {
  const { user } = useAuth();
  const { data } = useSuspenseQuery(dashboardQuery(user as NonNullable<typeof user>));
  const isAdmin = user?.roles.some((role) => ["SUPER_ADMIN", "SUB_ADMIN"].includes(role));
  const isFinance = user?.roles.includes("FINANCE_OFFICER");
  const activeMembers = data.members.find((item) => item.status === "ACTIVE")?.count ?? 0;
  const openValue = data.disbursements.reduce((sum, item) => sum + item.value, 0);
  const awaiting = data.disbursements.filter((item) => ["SUBMITTED", "BRANCH_APPROVED", "FINANCE_REVIEW"].includes(item.stage)).reduce((sum, item) => sum + item.count, 0);
  return <div className="mx-auto max-w-[1440px] space-y-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">{user?.branch?.code ?? "Portfolio view"}</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-foreground">Good morning, {user?.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-muted-foreground">Here is the operational picture for your {isAdmin ? "organisation" : "workspace"}.</p></div><Badge variant="outline" className="w-fit gap-2 border-primary/20 bg-primary/5 px-3 py-1.5 text-primary"><span className="size-1.5 rounded-full bg-primary" />Live mock environment</Badge></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="Active members" value={compact.format(activeMembers)} detail={user?.branch ? "In your branch" : "Across all branches"} /><Metric icon={HandCoins} label={isFinance ? "Pipeline value" : "Open disbursements"} value={money.format(openValue)} detail={`${awaiting} currently awaiting action`} /><Metric icon={FileCheck2} label="Open reconciliations" value={String(data.openReconciliation)} detail="Items need review" tone="warning" /><Metric icon={Clock3} label="Pending handovers" value={String(data.pendingHandovers).padStart(2, "0")} detail={data.pendingHandovers ? "Require attention" : "No action required"} /></div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><h2 className="font-serif text-xl font-semibold">{isFinance ? "Payment pipeline" : "Portfolio activity"}</h2><p className="mt-1 text-xs text-muted-foreground">Current workload by workflow stage</p></div><button className="flex items-center gap-1 text-xs font-semibold text-primary hover:underline">View details <ArrowUpRight className="size-3.5" /></button></div><div className="p-6"><div className="flex h-48 items-end gap-2 sm:gap-4">{data.disbursements.map((item) => <div key={item.stage} className="group flex min-w-0 flex-1 flex-col items-center gap-2"><div className="relative flex h-36 w-full items-end"><div className={`w-full rounded-t-sm transition-all group-hover:opacity-80 ${item.stage === "FINANCE_REVIEW" ? "bg-primary" : "bg-primary/20"}`} style={{ height: `${Math.max(item.count * 35, item.count ? 18 : 6)}%` }}><span className="sr-only">{item.count} items</span></div></div><span className="max-w-20 text-center text-[10px] leading-tight text-muted-foreground">{stageLabel(item.stage)}</span><span className="text-xs font-bold">{item.count}</span></div>)}</div></div></section><section className="border border-border bg-card"><div className="border-b border-border px-6 py-5"><h2 className="font-serif text-xl font-semibold">Member status</h2><p className="mt-1 text-xs text-muted-foreground">{user?.branch?.name ?? "All branches"}</p></div><div className="space-y-5 p-6">{data.members.map((item) => <div key={item.status} className="flex items-center gap-3"><span className={`size-2 rounded-full ${item.status === "ACTIVE" ? "bg-primary" : item.status === "PENDING" ? "bg-chart-4" : "bg-muted-foreground/40"}`} /><span className="flex-1 text-sm">{statusLabel(item.status)}</span><span className="text-sm font-semibold">{item.count}</span><div className="h-1.5 w-16 bg-muted"><div className="h-full bg-primary/40" style={{ width: `${Math.min(item.count * 22, 100)}%` }} /></div></div>)}</div></section></div>
    {isAdmin ? <BranchTable data={data} /> : <ActivityFeed data={data} role={roleLabel(user?.roles[0] ?? "BRANCH_MANAGER")} />}
  </div>;
}

function Metric({ icon: Icon, label, value, detail, tone = "default" }: { icon: typeof UsersRound; label: string; value: string; detail: string; tone?: "default" | "warning" }) { return <div className="border border-border bg-card p-5"><div className="flex items-start justify-between"><span className="flex size-9 items-center justify-center bg-primary/10 text-primary"><Icon className="size-4" /></span>{tone === "warning" && <CircleAlert className="size-4 text-chart-4" />}</div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 truncate text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
function ActivityFeed({ data, role }: { data: DashboardData; role: string }) { return <section className="border border-border bg-card"><div className="border-b border-border px-6 py-5"><h2 className="font-serif text-xl font-semibold">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">The latest events across your {role.toLowerCase()} view</p></div><div className="divide-y divide-border">{data.auditEvents.map((event) => <div key={event.id} className="flex items-center gap-4 px-6 py-4"><span className={`flex size-8 shrink-0 items-center justify-center rounded-full ${event.severity === "warning" ? "bg-chart-4/15 text-chart-4" : "bg-primary/10 text-primary"}`}>{event.severity === "warning" ? <CircleAlert className="size-4" /> : <CheckCircle2 className="size-4" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{event.label}</p><p className="mt-1 text-xs text-muted-foreground">{event.actor}</p></div><span className="text-xs text-muted-foreground">{event.time}</span></div>)}</div></section>; }
function BranchTable({ data }: { data: DashboardData }) { return <section className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><h2 className="font-serif text-xl font-semibold">Branch portfolio</h2><p className="mt-1 text-xs text-muted-foreground">A quick view of operational health across offices</p></div><button className="flex items-center gap-1 text-xs font-semibold text-primary hover:underline">Manage branches <ArrowUpRight className="size-3.5" /></button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-muted/40 text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-6 py-3 font-semibold">Branch</th><th className="px-6 py-3 font-semibold">Members</th><th className="px-6 py-3 font-semibold">Open value</th><th className="px-6 py-3 font-semibold">Status</th></tr></thead><tbody className="divide-y divide-border">{data.branches.map(({ branch, members, openValue: value, health }) => <tr key={branch.id}><td className="px-6 py-4"><span className="font-semibold">{branch.name}</span><span className="ml-2 text-xs text-muted-foreground">{branch.code}</span></td><td className="px-6 py-4">{members}</td><td className="px-6 py-4 font-medium">{money.format(value)}</td><td className="px-6 py-4"><Badge variant="outline" className={health === "On track" ? "border-primary/25 bg-primary/5 text-primary" : "border-chart-4/30 bg-chart-4/10 text-chart-4"}>{health}</Badge></td></tr>)}</tbody></table></div></section>; }